I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 13, in script
    t "this is tomoe's sprite"
Exception: Sayer 't' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 13, in script
    t "this is tomoe's sprite"
  File "D:\Users\fiona\Documents\Ren'Py\renpy\ast.py", line 624, in execute
    who = eval_who(self.who, self.who_fast)
  File "D:\Users\fiona\Documents\Ren'Py\renpy\ast.py", line 537, in eval_who
    raise Exception("Sayer '%s' is not defined." % who.encode("utf-8"))
Exception: Sayer 't' is not defined.

Windows-8-6.2.9200
Ren'Py 7.0.0.196
test 1.0
Sun Feb 24 20:25:10 2019
